### ISSUE TITLE
New version of ruby2ruby breaks rendering

### ISSUE THREAD

**Issue by tbrisker** [svenfuchs/safemode#24]
With ruby2ruby 2.3.2:
```
1] pry(main)> box = Safemode::Box.new
=> #<Safemode::Box:0x0000001350f5b0 @filename=nil, @line=nil, @scope=#<Safemode::Box:0x9a87ad8>
[2] pry(main)> box.eval('a')
Safemode::SecurityError: Safemode doesn't allow to access 'a' on #<Safemode::ScopeObject>
from /home/tbrisker/.rvm/gems/ruby-2.1.10@foreman_gemset/gems/safemode-1.3.2/lib/safemode/scope.rb:39:in `method_missing'
```

With ruby2ruby 2.4.0:
```
[7] pry(main)> box = Safemode::Box.new
=> #<Safemode::Box:0x00000010e1ca48 @filename=nil, @line=nil, @scope=#<Safemode::Box:0x870e524>
[8] pry(main)> box.eval('a')
NoMethodError: undefined method `first' for :call:Symbol
from /home/tbrisker/.rvm/gems/ruby-2.1.10@foreman_gemset/gems/safemode-1.3.2/lib/safemode/parser.rb:142:in `process_call_receiver'
```

**Comment by witlessbird** [comment]
Released gem v1.3.3 that should fix the issues introduced by Ruby2Ruby >= 2.4.0
